export { default as Dashboard } from './Dashboard';
export { default as LandingPage } from './LandingPage';
export { default as Login } from './Login';
export { default as CreatePlaylist } from './createPlaylist';
export {default as Error} from './Error';
export{default as SinglePlaylist} from './SinglePlaylist';
export {default as VideoCourse} from './VideoCourse';
export {default as VideoNotes} from './VideoNotes';
export {default as Scheduling} from './Scheduling';
export {default as Privacy } from './Privacy';